apiVersion: v1
kind: Service
metadata:
  name: beee-hexa-todo
  labels:
    app: hexa-todo
    component: microservice
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hexa-todo
  sessionAffinity: None
  type: ClusterIP