kind: Deployment
apiVersion: apps/v1
metadata:
  name: hexa-todo
  labels:
    app: hexa-todo
    component: microservice
spec:
  selector:
    matchLabels:
      app: hexa-todo
      component: microservice
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  progressDeadlineSeconds: 300
  template:
    metadata:
      name: hexa-todo
      labels:
        app: hexa-todo
        component: microservice
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: beee-hexa-todo
        image: hexabase.azurecr.io/beee-hexa-todo
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /health_check
            port: hexa-todo
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 3
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sleep", "20" ]
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits: {}
        imagePullPolicy: Always
        ports:
        - name: hexa-todo
          containerPort: 80
      - name: dnsmasq
        image: "janeczku/go-dnsmasq:release-1.0.7"
        args:
          - --listen
          - "127.0.0.1:53"
          - --default-resolver
          - --enable-search
        resources: {}
      nodeSelector:
        type: node00